matrix:
  include:
    - language: python
      dist: xenial
      python: 3.7
      before_install:
        - pip install poetry
      install:
        - poetry install
      script:
        - poetry run flake8
        - poetry run py.test
